{% set name = "namae" %}
{% set version = "1.1.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 14f8a98ff82e2d0476d845aa4421dc142345308581b9de72f56ff44967a076c8

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: {{ name }}-{{ version }}/BSDL
  summary: Namae (名前) is a parser for human names.

  description: |
    It recognizes personal names of various cultural backgrounds and tries to split
    them into their component parts (e.g., given and family names, honorifics etc.).
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/berkmancenter/{{ name }}

extra:
  recipe-maintainers:
    - sodre
