travis:
  secure:
    BINSTAR_TOKEN: sQlSd9sidQG/ByqYWHl1yoSmtUtLRKtoRdo5SLqpJ+ceuFC8ekE86YrWI0jPeQa8Wj9jwYkID/QhK3qzDQax3c0ZLP6gRhXCwapyNV6gfEcnBP7ssVDJDeuJsH4eYO6pyp6MSx9/Mpy9WDFEEWbGfqg87Ugyliqfnpj9V1azY2Xs+HYG3xcWykKTXfGFkEmWyq12FQwsgaUC6thDLUMYmLb7sNc6EU6pZBBBs/Ae9axoeVhs0qX73O0Hvlh537lDlZllRvZU0kLhB4Ar2H0El8SSGu+pjEoY0MohIMhexGCIblFilMfLqj4JsnUb8HoBMr5rxzVaFDGTE2rMRRhVYgOOx7DFEZiLx4a3N03x/frd9dp7KRuptY8w0Yef9FyMfe4gYR5A7xnj+q69ZBOpUBb8PSd27T1xNxSAMP3koH/tzc8f6qmpnjotseNEdIuk03GjC+6juJBlJchKWdZiAWaEJICaAX/8z7Ve9wTsZgxDLgh0M8bMrXXowa/6QtmDIYIRfZVGfhoT/SREQSloWOy1/RwvXmw0IHMwaEYleU/RFordtTHpS0FI2gkLubQAmbAW3Hp1/gYXA8sC1zvF1rEyQl+1yuf9blZuNx+Rzq8tvIA3zSR/QVbB9lobSJH4YfiK1qdUlQE50IiMrNqCFPqe1aORcNH90qu0Bn76JcA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
